# coding=utf-8

#this is the training data set containing gramatically correct sentences in hindi for the corresponding engish sentences.
data_set = [
("Help!","बचाओ!"),
("Hello!","नमस्ते।"),
("I'm OK","मैं ठीक हूँ।"),
("Come in","अंदर आ जाओ"),
("Get out","बाहर निकल जाओ"),
("Goodbye","ख़ुदा हाफ़िज़"),
("Welcome","आपका स्वागत है"),
("I'm fine","मैं ठीक हूँ"),
("Let's go","चलो चलें"),
("I laughed","मैं हँसा"),
("I'm tired","मैं थक गया हूँ"),
("It's cold","ठंड हो रही है"),
("Don't move","हिलो मत"),
("I can swim","मुझे तैरना आता है"),
("I love you","मुझे तुमसे प्यार है"),
("I will try","मैं कोशिश करूँगा"),
("Please sit","बैठिए"),
("How are you?","आप कैसे हैं?"),
("I like dogs","मुझे कुत्ते अच्छे लगते हैं"),
("I am at home","मैं घर पर हूँ"),
("I don't know","मुझे नहीं पता"),
("I have a car","मेरे पास एक गाड़ी है"),
("It is a book","यह किताब है"),
("Please leave","कृपया जाईये"),
("Can you drive","तुम गाड़ी चला सकते हो क्या"),
("Everyone dies","मौत तो सभी की होती है"),
("I'm very busy","मैं बहुत व्यस्थ हूँ"),
("Make it quick","जल्दी कीजिए"),
("Open the door","दरवाज़ा खोलो"),
("Read it aloud","पढ़के सुनाओ"),
("This is a map","यह नक्शा है"),
("Can I help you?","क्या मैं आपकी सहायता कर सकता हूँ?"),
("Happy New Year","नए साल की बधाईयाँ"),
("Happy birthday","जन्मदिन मुबारक हो"),
("He is an actor","वह अभिनेता है"),
("I like history","मुझे इतिहास पसंद है"),
("I'll phone you","मैं तुम्हें फ़ोन करूँगा"),
("I'm an atheist","मैं भगवान में यकीन नहीं करता"),
("Take your time","आराम से आओ"),
("This is a book","यह एक किताब है"),
("This is my bag","यह मेरा बस्ता है"),
("We study music","हम संगीत की पढ़ाई करते हैं"),
("Where were you","तुम कहाँ थे"),
("Are you at home","तुम घर पे हो क्या"),
("Come home early","जल्दी घर आजाओ"),
("He came running","वह भागते हुए आया"),
("How is everyone","सब लोग कैसे हैं"),
("I run every day","मैं रोज़ दौड़ने जाता हूँ"),
("Open your mouth","अपना मूँह खोलो"),
("Please sit down","बैठिए"),
("She talks a lot","वह बहुत बोलती है"),
("These are birds","ये चिड़ियाँ हैं"),
("Where's my book","मेरी किताब कहाँ है"),
("Are you a doctor","आप डॉक्टर हैं क्या"),
("Can you teach me","क्या तुम मुझे सिखा सकते हो"),
("Have a good time","मज़े करो"),
("He likes oranges","उसे संत्रे अच्छे लगते हैं"),
("I don't know him","मैं उसे नहीं जानता"),
("I love my mother","मैं अपनी माँ से प्यार करता हूँ"),
("Nice to meet you","आपसे मिलकर खुशी हुई"),
("The car is ready","गाड़ी तैयार है"),
("What is your age","तुम्हारी उम्र क्या है"),
("I can drive a car","मैं गाड़ी चला सकता हूँ"),
("I got very sleepy","मुझे नींद आ गई"),
("I have a headache","मेरे सिर में दर्द हो रहा है"),
("My eyes are tired","मेरी आँखें थक गईं हैं"),
("Tell me the truth","मुझे सच्चाई बताओ"),
("Turn on the radio","रेडियो को चालू करो"),
("We have good news","हमारे पास खुशखबर है"),
("What is your name","आपका नाम क्या है"),
("Where do you live","आप कहाँ रहते हैं"),
("Are you busy today","तुम्हारे पास आज समय है क्या"),
("Don't give up hope","उम्मीद मत छोड़ो"),
("Everyone likes him","उसे सब पसंद करते हैं"),
("He is a simple man","वह साधा आदमी है"),
("I can read English","मैं अंग्रेज़ी पढ़ सकता हूँ"),
("The power went out","बिजली चली गई"),
("What's the problem","मुश्किल क्या है"),
("Answer my questions","मेरे सवालों का जवाब दो"),
("How did you make it","तुमने कैसे बनाया"),
("I do not understand","मैं समझा नहीं"),
("The man lost all hope","उस आदमी ने सारी उम्मीद छोड़दी"),
("A fox is a wild animal","लोमड़ी जंगली जानवर होती है"),
("Everyone knew the song","वह गाना सभी को पता था"),
("He will soon come back","वह बस अभी आता होगा"),
("Take good care of yourself","अपना अच्छे से ख़याल रखना"),
("The rain continued all day","बरसात पूरे दिन होती रही"),
("This is the monsoon season","यह वर्षा ऋतु का मौसम है"),
("Turn off the light"," please","कृपया बत्ती बंद कर दीजिए"),
("We should keep our promise","हमे अपना वादा निभाना चाहिए"),
("A day has twenty-four hours","एक दिन में चौबीस घंटे होते हैं"),
("Could you speak more slowly","थोड़ा धीरे बोल सकते हैं क्या"),
("I will call on him tomorrow","मैं कल उससे मिलने जाऊँगा"),
("It is a sheer waste of time","यह सरासर समय की बर्बादी है"),
("It was too difficult for me","वह मेरे लिए बहुत कठिन था"),
("Please give me a cup of tea","मुझे एक कप चाय दीजिए"),
("Smoking is not allowed here","यहाँ धूम्रपान करना मना है"),
("Thank you","धन्यवाद"),
("The store is not open today","दुकान आज बंद है"),
("Correct the underlined words","रेखांकित शब्दों को सुधारिए")
]
